import { test, expect } from '../../fixtures/base';

// Visual baseline for the Add contact drawer: a static form (the list behind it changes with data, so only
// the drawer is captured). Golden file generated by Playwright itself via --update-snapshots on first run.
test('Add contact drawer matches visual baseline', async ({ page, contactsPage }) => {
  await contactsPage.goto();
  await contactsPage.openAddContact();
  await expect(contactsPage.firstName).toBeVisible();
  await expect(page).toHaveScreenshot('add-contact-drawer.png', {
    clip: { x: 820, y: 0, width: 620, height: 900 },
    animations: 'disabled',
  });
});

test('Add deal drawer matches visual baseline', async ({ page, dealsPage }) => {
  await dealsPage.goto();
  await dealsPage.openAddDeal();
  await expect(page.getByText('Deal stage', { exact: true })).toBeVisible();
  await expect(page).toHaveScreenshot('add-deal-drawer.png', {
    clip: { x: 820, y: 0, width: 620, height: 900 },
    animations: 'disabled',
    mask: [page.locator('input[name="deal[name]"]')],
  });
});
