import { test, expect } from '@playwright/test';
import { SettingsPage, PATHS } from '../../../pages/settings-data-model/SettingsPage';

// Golden baselines are generated by Playwright itself (--update-snapshots) in this project; explore screenshots are reference only.
test.describe('Settings data model: visual baselines', () => {
  test('Contact Lifecycle Stages page', async ({ page }) => {
    const s = new SettingsPage(page);
    await s.goto(PATHS.lifecycle, s.addStageBtn);
    await expect(s.stageCard('Lead')).toBeVisible();
    await expect(page.getByText("Whenever a deal is added, change contact's stage to").first()).toBeVisible();
    await expect(page).toHaveScreenshot('lifecycle-stages.png', { mask: [page.locator('[class*="toast"]')], animations: 'disabled' });
  });

  test('Contact Scoring page', async ({ page }) => {
    const s = new SettingsPage(page);
    await s.goto(PATHS.scoring, page.getByText('Add signal', { exact: true }).first());
    await expect(s.btn('Save settings')).toBeDisabled();
    await expect(page).toHaveScreenshot('contact-scoring.png', { animations: 'disabled' });
  });

  test('Record Tags page (dates masked)', async ({ page }) => {
    const s = new SettingsPage(page);
    await s.goto(PATHS.tags, s.tagInput);
    await expect(s.tagRows.first()).toBeVisible();
    await expect(page).toHaveScreenshot('record-tags.png', { mask: [page.locator('.relative-date'), page.locator('table tbody td:nth-child(5), table tbody td:nth-child(6)')], animations: 'disabled' });
  });

  test('Custom Modules empty state', async ({ page }) => {
    const s = new SettingsPage(page);
    await s.goto(PATHS.modules, page.getByText('No custom modules found.'));
    await expect(page).toHaveScreenshot('custom-modules-empty.png', { animations: 'disabled' });
  });
});
